### ISSUE TITLE
how to build/install?

### ISSUE THREAD

**Issue by dan-da** [rsbondi/clightning-go-plugin#1]
thx for this plugin.

Can you add basic build/install instructions that someone who is not a go developer or an expert on c-lightning plugins can follow to achieve working installation.   thanks!

**Comment by rsbondi** [comment]
I added [general installation](https://github.com/rsbondi/clightning-go-plugin#general-plugin-installation) instructions for the repo and I added a binary for the `dump_keys` plugin, please take a look and close this issue if satisfactory, thanks.

**Comment by dan-da** [comment]
looks great, thanks!
